# Generated by Django 5.1.3 on 2024-11-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shorter', '0005_remove_link_user'),
        ('user_profile', '0002_remove_profile_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
