# Generated by Django 5.1.3 on 2024-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
